'on':
  push:
    branches:
      - '*'
  pull_request: null
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        working-directory: ./rust
        with:
          command: check
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        working-directory: ./rust
        with:
          command: test
  lints:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: 'rustfmt, clippy'
      - uses: actions-rs/cargo@v1
        working-directory: ./rust
        with:
          command: fmt
          args: '--all --check'
      - uses: actions-rs/cargo@v1
        working-directory: ./rust
        with:
          command: clippy
          args: '-- -D warnings'
